baseURL = 'https://xfsnowind.github.io'
languageCode = 'en-us'
title = 'xfsnowind'
theme = "hugo-clarity"
enableRobotsTXT="true"

defaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
